---
output:
  pdf_document: 
    fig_caption: yes
    toc: yes
  html_document: default
title: Develop cleaning algorithm
---



```{r setup, message=FALSE, warning=FALSE, echo=FALSE}
library(knitr)
opts_knit$set(root.dir="..") # file paths are relative to the root of the project directory
opts_chunk$set(echo = FALSE)
library(eutradeflows)
library(dplyr)
library(tidyr)
library(magrittr)
library(ggplot2)
``` 


See  also `/tradeflows/docs/development/cleaning/Comext.Rmd`.
In that document, tradeflows functions (originally written for Comtrade) 
are tested on the Comext data.

```{r databasetableanalysed, echo=FALSE}
# Comment out to pass tableanalysed as a parameter in the parent environment
recenttable <- 'raw_comext_monthly_201708' 
archivetable <- 'raw_comext_monthly_2016S1'
productanalysed <- 44072960
con <- RMySQL::dbConnect(RMySQL::MySQL(), dbname = "tradeflows")
```

# Introduction

Steps of the cleaning process

 * Calculate prices and conversion factors, storred in a table called
 vld_comext_pricecv
 * 

```{r echo = FALSE}


```
    
