---
title: "MySQL Commands"
author: "Paul Rougieux"
date: "25 August 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Dump

## Load a dump
The following commands can be used to load mysql dump files:
```{bash eval=FALSE}
7zr e raw_comext_monthly_201708.sql.7z
cat raw_comext_monthly_201708.sql | mysql tradeflows
```


## Create a dump
[how to compress a mysqldump with 7z via a pipe?](https://unix.stackexchange.com/questions/232006/how-to-compress-a-mysql-dump-using-7z-via-a-pipe)
First version needed to make sure the archive doesn't exist already 
other wise it would contain the SQL dump twice.
See Paul's question on stackexchange 
[How to overwrite content in a 7z archive created from a pipe?](https://unix.stackexchange.com/questions/386913/how-to-overwrite-content-in-a-7z-archive-created-from-a-pipe)
The answer is to supply a name for the file generated from standard input, 
within the `-si` option, such as `-sifilename`.
```{bash eval=FALSE}
# prefer 7zr to 7z as this is the only one available on the server
cd _server_path_/sqldump

# Recent data
mysqldump tradeflows raw_comext_monthly_201708 | 7zr a -siraw_comext_monthly_201708.sql raw_comext_monthly_201708.sql.7z

# Monthly archive
mysqldump tradeflows raw_comext_monthly_2016S1 | 7zr a -si raw_comext_monthly_2016S1.sql.7z

# Dump validated codes
mysqldump tradeflows val_comext_product | 7zr a -si val_comext_product.sql.7z
mysqldump tradeflows val_comext_reporter | 7zr a -si val_comext_reporter.sql.7z
mysqldump tradeflows val_comext_partner | 7zr a -si val_comext_partner.sql.7z
```

Create an R function that dumps a database table to a given folder location.
If the archive exists already, do not recreate it, unless force=TRUE.
    If force=TRUE, delete the archive.
If the archive doesn't exist, 
compress the output of mysqldump and store it in the given folder.

Create an R function that dumps all tables in the trade flows database, 
each table in a separate .sql.7z file.

Create an R function that dumps all tables containing a given pattern in 
their names, such as "monthly" or "yearly".
